// <auto-generated />
using System;
using Joaoafonsosite.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Joaoafonsosite.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Joaoafonsosite.Domain.Entities.Trabalhos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataDeCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataDeEdicao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Duracao")
                        .HasColumnType("float");

                    b.Property<string>("Imagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoftwareUsado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Tamanho")
                        .HasColumnType("float");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trabalho");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Animação de comboio, noturna .",
                            Duracao = 0.5,
                            Imagem = "https://placehold.co/600x400",
                            Nome = "Train to Tokyo",
                            SoftwareUsado = "Blender, After Effects",
                            Tamanho = 50.0,
                            Tipo = "Animação"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Animação, floresta, cogumelos, borboletas.",
                            Duracao = 0.5,
                            Imagem = "https://placehold.co/600x401",
                            Nome = "Glowing Mushroom",
                            SoftwareUsado = "Blender",
                            Tamanho = 120.0,
                            Tipo = "Animação"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Animação morgue abandonada, luzes a piscar ambiente de terror.",
                            Duracao = 0.5,
                            Imagem = "https://placehold.co/600x402",
                            Nome = "Rigor Mortis",
                            SoftwareUsado = "Blender",
                            Tamanho = 80.0,
                            Tipo = "Animação"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
